services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: trivia_user
      POSTGRES_PASSWORD: trivia_password
      POSTGRES_DB: trivia_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trivia_user -d trivia_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    environment:
      DATABASE_URL: postgresql://trivia_user:trivia_password@db:5432/trivia_db
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
