name: Python CI

on: [push, pull_request] 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11'] 

    
    env:
      PYTHONHASHSEED: 0
      RANDOM_SEED: 12345 

    steps:
    - name: Checkout repository 
      uses: actions/checkout@v4 

    - name: Set up Python ${{ matrix.python-version }} 
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -r belly_project/requirements.txt

    - name: Run unit tests with pytest 
      run: |
        cd belly_project
        pytest tests/ --cov=src --cov-report=term-missing --cov-report=xml

    - name: Run ALL BDD tests with behave 
      run: |
        cd belly_project
        behave features/

    - name: Run Spanish BDD tests
      run: |
        cd belly_project
        behave features/ --tags=@language_spanish

    - name: Run English BDD tests
      run: |
        cd belly_project
        behave features/ --tags=@language_english

    - name: Run Performance BDD tests
      run: |
        cd belly_project
        behave features/ --tags=@performance

    - name: Upload coverage reports to Codecov 
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }} 
        file: ./belly_project/coverage.xml
        fail_ci_if_error: true

    - name: Upload coverage report as artifact 
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-${{ matrix.python-version }}
        path: ./belly_project/coverage.xml 